### ISSUE TITLE
Le revisioni editoriali

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/gestione_testo#1]

**Comment by Teodoro777** [comment]
Qui mo andiamoci piano perché queste erano tutte cose nuove per me

Il martedì 9 febbraio 2016, Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
ho aggiunto solo due tag, `<del>` e `<ins>`.
Non sono molto importanti, ma utili a capire il meccanismo

**Comment by Teodoro777** [comment]
Il del vabbè ma già ins ha più cose da ricordare

Il mercoledì 10 febbraio 2016, Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
`<ins>` prevede gli attributi `datetime` e `cite`. Una volta che hai capito il meccanismo se poi serve si cerca su internet

**Comment by Teodoro777** [comment]
Sì infatti

Il mercoledì 10 febbraio 2016, Fabio Z Tessitore <notifications@github.com>
ha scritto:
