### ISSUE TITLE
Tweets

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/gestione_testo#10]
Crea una pagina tweets.html in cui sia presente
una lista di tweets. Scegli con attenzione gli
elementi di cui e' formato un singolo tweet.

**Comment by Teodoro777** [comment]
Che roba è un tweet!?

2016-02-22 20:18 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
Non conosci Twitter?

Il martedì 23 febbraio 2016, Teodoro <notifications@github.com> ha scritto:

**Comment by Teodoro777** [comment]
Sì certo, ma un tweet è un post

Il martedì 23 febbraio 2016, Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
Eh. Prova a inventarti una struttura di elementi html che lo descrive

Il martedì 23 febbraio 2016, Teodoro <notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
per quello che stiamo facendo ora va bene. Però name e username potevano andare in un altro div (author per esempio) a cui si poteva aggiungere la pic.
Invece l'hastag non necessita di un div separato.
Volendo si poteva aggiungere un div per i pulsanti
