### ISSUE TITLE
Il testo

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/gestione_testo#2]

**Comment by Teodoro777** [comment]
Questi invece li so

Il mercoledì 10 febbraio 2016, Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
Molti tag si utilizzano per dare significato al testo.

Cosi' come p indica un paragrafo, h1 .. h6 le intestazioni abbiamo anche:

```html
<abbr>      abbreviazioni
<acronym>   acronimi
<cite>      citazioni
<code>      codice sorgente
<dfn>       termini da definire
<em>        evidenza
<strong>    evidenza forte
<kbd>       da inserire con la tastiera
<samp>      testo di esempio
<var>       variabili
<pre>       testo preformattato
<address>   dati di contatto
```

**Comment by Teodoro777** [comment]
Ok

Il giorno 10 febbraio 2016 22:20, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
Issue
Alcuni caratteri hanno un significato speciale
e non possono essere inseriti direttamente nelle pagine Web.

I simboli `<` e `>` per esempio servono a delimitare i tag.

In questi casi si utilizzano dei codici:
```html
&lt;    (less than)     minore
&gt;    (greater than)  maggiore
&amp;   (ampersand)     &
```

Anche per le lettere accentate vale un discorso analogo:
```
&eacute;  é
&egrave;  è
&ograve;  ò
...
```

**Comment by Teodoro777** [comment]
Ok

Il venerdì 12 febbraio 2016, Fabio Z Tessitore <notifications@github.com>
ha scritto:
