### ISSUE TITLE
esercitazione: il linguaggio C

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/gestione_testo#3]
![linguaggioc_pt1](https://cloud.githubusercontent.com/assets/3002194/13010149/bfba0c7a-d1a0-11e5-9fbf-4d53621266a8.png)
![linguaggioc_pt2](https://cloud.githubusercontent.com/assets/3002194/13010155/c4c862ac-d1a0-11e5-98ea-b688cb67e492.png)

Cerca di ottenere questo risultato

**Comment by Teodoro777** [comment]
Ok ho letto, cosa devo fare?

2016-02-12 15:54 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by Teodoro777** [comment]
Comunque mi spiegate la differenza tra union, enum e struct?

Il giorno 12 febbraio 2016 21:14, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
devi creare una pagina html cercando di ottenere il risultato mostrato nell'immagine

**Comment by FabioZTessitore** [comment]
ci riusciamo?

**Comment by Teodoro777** [comment]
Alla fine <p> e <div>

2016-02-17 14:29 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by Teodoro777** [comment]
sono uguali?!

Il giorno 17 febbraio 2016 19:05, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by Teodoro777** [comment]
Fatto

Il giorno 17 febbraio 2016 19:05, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:
