### ISSUE TITLE
caratteri speciali

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/gestione_testo#8]
ti ricordo che `<` e `>` rientrano tra quei caratteri speciali che non puoi inserire nella pagina (vedi la parte relatica al codice di esempio)

**Comment by FabioZTessitore** [comment]
mancano i ;

**Comment by Teodoro777** [comment]
Nel programma ci stanno

2016-02-20 12:13 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
non nel programma. I caratteri speciali terminano con il ;

**Comment by Teodoro777** [comment]
Ahah funzionava lo stesso

2016-02-21 12:57 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
i browser perdonano molte cose, ma questo non significa che bisogna lavorare male

**Comment by Teodoro777** [comment]
Si infatti 

Inviato da iPad
