### ISSUE TITLE
id e class

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/gestione_testo#9]
Ho aggiunto il file posts.html

**Comment by Teodoro777** [comment]
Non ho capito bene quando usare l'uno o l'altro

2016-02-22 19:52 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
```html
<!-- l'attributo id permette di identificare
      un elemento della pagina in maniera univoca.
      Solo un elemento in questa pagina 
      puo' avere id pari a "posts" -->
    <div id="posts">
```

**in maniera univoca** significa che solo un elemento della pagina può avere id="posts"

invece una class serve a specificare una categoria. Nel caso dell'esempio i "post" (senza s) sono tanti e quindi usiamo class
